version: "3.8"
services:
  db-container-1:
    container_name: db_container_shop
    image: postgres:16.3
    environment:
      POSTGRES_USER: admin_shop_db
      POSTGRES_PASSWORD: Hoom-IT1337
      POSTGRES_DB: hoom_shop_db
    ports:
      - "127.0.0.1:5432:5432"