version: "3.8"
services:
  db-container-1:
    container_name: db_shop_container
    image: postgres:16.3
    environment:
      POSTGRES_USER: admin_shop_db
      POSTGRES_PASSWORD: Hoom-IT1337
      POSTGRES_DB: hoom_shop_db
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - v_shop_db:/var/lib/postgresql
    restart: always
  pgadmin:
    container_name: pgA_db_shop_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: marashi.nima@outlook.de
      PGADMIN_DEFAULT_PASSWORD: Hoom-IT1337-pg
    ports:
     - 127.0.0.1:5050:80